### ISSUE TITLE
Pre trained model

### ISSUE THREAD

**Issue by techverve** [towardsautonomy/VR3Dense#4]
Hey fellow dev, amazing work with your paper + code, one of the finest contributions in this domain. I am raising this issue in request to share the trained models wandb. I wanted to know if its possible to get it?

**Comment by towardsautonomy** [comment]
Hi Jeff, When you follow the ‘Demo’ section of README and run given test script, it should download the pre-trained model and then run the demo. The pretrained model park is defined here (https://github.com/towardsautonomy/VR3Dense/blob/6f58724eb5dd0b28aafb17a24747054547e21a57/src/utils/vr3d_utils.py#L21) which can be downloaded from google drive if you wish to do so.

**Comment by towardsautonomy** [comment]
I hope that this helped, I am closing this issue - feel free to reopen if the issue persists.
